### ISSUE TITLE
Lots of traffic on mdns port, but avahi-browse shows only local items

### ISSUE THREAD

**Issue by jdtsmith** [lathiat/avahi#151]
Raspberry Pi Zero with Raspbian Stretch.  I have `avahi-daemon`:

```
Source: avahi
Version: 0.6.32-2
Architecture: armhf

```

and:

```
Package: libnss-mdns
Source: nss-mdns
Version: 0.10-8
```

Only after freshly starting `avahi-daemon` is this host resolvable as `host.local` from other machines on the network.  But after a few minutes, it stops responding, and a restart of the `avahi-daemon` is the only thing that will get it resolving again.  

Perhaps related, as well, on the host itself, `avahi-browse -atr` usually shows only `local` items (e.g. internet printer exposed by `CUPS`).  No other hosts can be resolved in the `.local` domain.  Other machines on this network connected in the same manner (ethernet) see a full complement of several dozen items.  To investigate this, I monitored traffic on the offending host `mdns` port:

```
sudo tcpdump -i enx00e04c534458 port 5353
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enx00e04c534458, link-type EN10MB (Ethernet), capture size 262144 bytes
01:33:42.743606 IP [] > 224.0.0.251.mdns: 0 [2q] SRV (QU)? Officejet J6400 series [416B15]._pdl-datastream._tcp.local. TXT (QU)? Officejet J6400 series [416B15]._pdl-datastream._tcp.local. (82)
01:33:42.881235 IP [].local.mdns > 224.0.0.251.mdns: 0 PTR (QM)? 38.0.168.192.in-addr.arpa. (43)
01:33:43.053659 IP []-891.local.mdns > 224.0.0.251.mdns: 0*- [0q] 1/0/1 (Cache flush) PTR []-891.local. (93)
01:33:43.183132 IP [].local.mdns > 224.0.0.251.mdns: 0 PTR (QM)? 251.0.0.224.in-addr.arpa. (42)
01:33:43.749650 IP []-891.local.mdns > 224.0.0.251.mdns: 0 [2q] SRV (QM)? Officejet J6400 series [416B15]._pdl-datastream._tcp.local. TXT (QM)? Officejet J6400 series [416B15]._pdl-datastream._tcp.local. (82)
01:33:44.184413 IP [].local.mdns > 224.0.0.251.mdns: 0 PTR (QM)? 251.0.0.224.in-addr.arpa. (42)
01:33:46.187391 IP [].local.mdns > 224.0.0.251.mdns: 0 PTR (QM)? 251.0.0.224.in-addr.arpa. (42)
01:33:48.214616 IP [].local.mdns > 224.0.0.251.mdns: 0 PTR (QM)? 197.0.168.192.in-addr.arpa. (44)
...
```

(trimmed with `[]`), and noticed plenty of traffic.  But subsequent calls to `avahi-browse` did **not** show any of these items which had just been seen to arrive on port 5353, but still listed only `local` items.  Needless to say, `hostname.local` resolving also failed to work.  Occasionally, this disconnect will briefly subside and `avahi-browse` shows a full list including all network-reachable items, but then shortly after would be lost.  This host is a connected with a micro-USB ethernet dongle (hence the `enx00...` above instead of `eth0`).  

I have another Raspberry PI (3) with builtin ethernet and identical versions running that does not exhibit this behavior.  Both are connected to the same router (Hitron unit from cable company).

Thanks for any pointers or leads.

**Comment by lathiat** [comment]
It’s almosf certainly bad support for multicast in the driver for your USB Ethernet dongle. More common in wifi drivers but you see this same behaviour. 

Does it work if you leave tcpdump running and then restart avahi?

**Comment by lathiat** [comment]
(This often works because it puts the interface into promiscuous mode and thus received all packets instead of the hardware filtering out the multicast packets)

**Comment by jdtsmith** [comment]
Thanks, and good call... indeed it's after running `tcpdump` for a while that the cache fills up with real network items (only to stop later).   I can test this again later tonight but quite certain that's the case.  So the idea is that `tcpdump` enables promiscuous mode, so it can see the `mdns` traffic while `avahi` cannot?  Any pointers on correcting this? Just enable promiscuous mode?

**Comment by lathiat** [comment]
Basically the way multicast works, it's send to a "special" MAC address other than the one of your Ethernet adaptor.

Most network devices filter out traffic not destined for the MAC address of your device or other MACs in a list usually programmed by the kernel driver including Multicast and possibly some other MAC addresses (for example if you were bridging to virtual machines, the MAC of each of the virtual machines would also be programmed into the network card).  The general idea behind this filter list is power savings.

Kernel device drivers specifically have logic to program this list for multicast subscriptions, which generally work fine but sometimes on more obscure and usually embedded drivers they author did not complete the driver and get that working.  It's basically just broken/incomplete.

Promiscuous mode works around the issue by telling the network card to just send through all packets, and not filter anything.  By effect, all multicast packets then get passed on.  It's a hack (rather than a solution).

You can enable promiscuous without tcpdump by doing:
ip link set enx00e04c534458 promisc on

In some cases you can also run "ip link set enx00e04c534458 allmulti on" but that works less commonly.

You could maybe put that in a boot script or something as a workaround.. otherwise maybe you can find a newer kernel with a fixed driver.

**Comment by jdtsmith** [comment]
Thanks.  Just in case anyone finds this with a similar issue: not an `avahi` bug but a poorly supported cheap micro-USB ethernet dongle.  Try `lsusb` to see what device you have.  Some info about the poor Davicom96XX unit I have [here](https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=34557).  Enabling promiscuous mode as suggested is a temporary workaround and does allow `mdns` packets to flow, but I'll look into to replacing this unit (which was in the linux device "hall of shame" apparently).  On the outside it says model 9700.  Thanks again.
