### ISSUE TITLE
avahi-daemon: Failed to open /etc/resolv.conf: Invalid argument

### ISSUE THREAD

**Issue by rdieter** [lathiat/avahi#153]
Seems if avahi is started before NetworkManager fully enumerates network interfaces (which it does asynchronously), logs complain of missing resolv.conf

avahi-daemon[706]: chroot.c: open() failed: No such file or directory
avahi-daemon[692]: Failed to open /etc/resolv.conf: Invalid argument

One downstream user suggests adding to avahi-daemon.service:
After=network-online.target
to [Unit] section, which does indeed seem to help.  Not sure if that's the best/only solution though.

See also:
https://bugzilla.redhat.com/show_bug.cgi?id=1356304

**Comment by rond14** [comment]
Hello, I have the same messages in my log.

-- Version: avahi-daemon  0.7-3.1

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (500, 'testing')
Architecture: amd64 (x86_64)

Kernel: Linux 4.15.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=fr_FR.UTF-8, LC_CTYPE=fr_FR.UTF-8 (charmap=UTF-8), LANGUAGE=fr_FR.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

**Comment by sourcejedi** [comment]
`avahi-daemon` appears to support and require SIGHUP to reload changes to `resolv.conf`. So I'm more inclined in the direction of

> I'm tempted to change
> `avahi_log_error(__FILE__": open() failed: %s", strerror(errno));`
> to 
> `avahi_log_warn(...)`

Except surely the real fix is for the chroot helper not to log at all, but reply with an `errno`, for the main process... which needs to gain `file_get_contents_if_exists()`...

**Comment by mvduin** [comment]
The features for which avahi-daemon needs access to `resolv.conf` are quite obscure, so in most cases you probably just want to suppress the error.  While delaying the startup of avahi may work, I would instead suggest creating a config file in `/etc/tmpfiles.d` that makes sure a file exists at the target location of the symlink, e.g.:
```
f /run/NetworkManager/resolv.conf - - - -
```
This will, at very early boot, create directory `/run/NetworkManager` (root/root rwxr-xr-x) if it doesn't already exist and create an empty file `/run/NetworkManager/resolv.conf` (root/root rw-r--r--) if it doesn't already exist.

If you do want to make proper use of the avahi features for which it needs `resolv.conf` then delaying avahi's startup is still not a great fix since there's many situations where its contents may change while avahi is running. The only proper fix would be for avahi to monitor it for changes.

I would certainly vote for not giving an error or even a warning about getting ENOENT for resolv.conf, it's just pointless noise.

**Comment by evverx** [comment]
I think it's part of https://github.com/lathiat/avahi/issues/118.
