### ISSUE TITLE
s/UNCOMMITED/UNCOMMITTED/g

### ISSUE THREAD

**Issue by peternewman** [lathiat/avahi#167]
As found by https://github.com/lucasdemarchi/codespell . I guess this may want backwards compatibility of enums etc?

**Comment by warmsocks** [comment]
I ran codespell on the current master codebase, and it found other typos and misspellings too.  I'll submit a pull request with those fixed.

**Comment by warmsocks** [comment]
#222 fixes this issue and a few dozen other minor English language issues, mostly in comments.

**Comment by EskoDijk** [comment]
I reviewed #222 and provided review comments there.

**Comment by evverx** [comment]
@jschleus sorry to bother you. I wonder if it would be possible to add `avahi` to Fossies to build codespell reports like https://fossies.org/linux/test/systemd-main.e30b4c1.230529.tar.gz/codespell.html? It should hopefully help to prevent PRs fixing the same typos.

**Comment by evverx** [comment]
The https://github.com/lathiat/avahi/tree/master/specs folder should probably be excluded if possible.

I'm not sure what happens when repository moves. In theory GitHub should keep redirecting lathiat/avahi to the new place but I'm not sure if it can affect Fossies somehow.

**Comment by jschleus** [comment]
> @jschleus sorry to bother you. I wonder if it would be possible to add `avahi` to Fossies to build codespell reports like https://fossies.org/linux/test/systemd-main.e30b4c1.230529.tar.gz/codespell.html? It should hopefully help to prevent PRs fixing the same typos.

@evverx No problem. The `Avahi` project contents page  can be found under https://fossies.org/linux/misc/avahi and the according codespell report (if available) under https://fossies.org/linux/misc/avahi/codespell.html.

Both version-independent URLs (the second one is not linked) should redirect always to the last release.

Perhaps more meaningful may be the continuously (!) updated codespell report for the Avahi GitHub "master" version which is available within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines:

https://fossies.org/linux/test/avahi-master.tar.gz/codespell.html

That version independent URL hopefully always redirects to the report for the latest "master" version identified by the short commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The refresh rate is currently half-hourly.

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (unsure I was about the variable name `calback``) please inform me if you find more of them so that I can force a new improved check if applicable.

Further information can be found under https://fossies.org/features.html#codespell.

**Comment by evverx** [comment]
> Perhaps more meaningful may be the continuously (!) updated codespell report for the Avahi GitHub "master" version which is available within a special restricted "test" folder

That's exactly what I was looking for. Thanks!

> if you find more of them so that I can force a new improved check

I think "Uncommited" at https://fossies.org/linux/test/avahi-master.ff2caff.230529.tar.gz/avahi-master/avahi-sharp/EntryGroup.cs?M=49#l_48 should probably be excluded. It's unfortunate that it's there but it is what it is.

I think it would make sense to add a link to the codespell report to README to make it easier for everyone to keep track of all the typos that need fixing. I think at least `systemd` stopped receiving bug reports about typos (because thanks to the Fossies badge it was clear that the project was aware of them) and started receiving PRs fixing typos in bulk (and that has saved at least some time for everyone I think).

**Comment by evverx** [comment]
I think it can be closed. Codespell is run regularly and the list of typos that need fixing can be found at https://fossies.org/linux/test/avahi-master.tar.gz/codespell.html.

**Comment by evverx** [comment]
> I think we want this information present somewhere in documentation

I think it should be possible to add the badge to README: [![Fossies codespell report](https://fossies.org/linux/test/avahi-master.tar.gz/codespell.svg)](https://fossies.org/linux/test/avahi-master.tar.gz/codespell.html). It should make it easier to find it. (I think it would probably make sense to add the Coverity and OSS-Fuzz badges too)

> Does it have some avahi project page? Does follow commits automatically or someone has to upload version to scan?

As far as I know https://fossies.org/linux/test/avahi-master.tar.gz/codespell.html is the avahi main page and it follows the master branch automatically. (@jschleus please correct me if I'm wrong)

> It seems it could be added to actions done during CI. Do we want that perhaps?

I think it would be great but it needs tweaking to weed out false positives. To judge from https://github.com/lathiat/avahi/pull/481 you're already aware of that :-)
