### ISSUE TITLE
allow /etc/avahi/hosts for domain other than .local

### ISSUE THREAD

**Issue by niconil** [lathiat/avahi#179]
I'm using avahi with a different domain
as the .local is used by an uncooperative Mi...oft server
i'm using domain .foo

but i discover that i can't declare
myrouter.foo 
in /etc/avahi/hosts

can you confirm that ?
so i can't add easely populate my foo domain with other entries.
is it possible to change that (feature request) ?

**Comment by ericse** [comment]
Avahi implement the mDNS protocol, which exclusively use the .local domain. 
What do you mean by "uncooperative server" ?

**Comment by niconil** [comment]
the resaon is few years old ...
i've google this "avahi local microsoft server"
and by example i find this blog article : 
http://smallbusiness.chron.com/resolving-local-ubuntu-38861.html

**Comment by ericse** [comment]
So you have a windows server which manage the .local domain with his DNS (unicast DNS), right?
This is unfortunate because .local should be reserved to mDNS (multicast DNS) like Avahi, and using another domain does not make great sense, as you would have to modify accordingly all the clients.
IMHO either you can change the domain used by the windows server, or abandon the idea of using Avahi on the same network.

**Comment by ericse** [comment]
Ok, thanks for the explanations, I just wanted to better understand your use case. Well, Avahi is open-source, so I guess it's a functionality nobody needed before, and you certainly can suggest it to the developers.

**Comment by niconil** [comment]
i'm not a native english speaker and i try to suggest it in my first message (i talked of a 'feature request')

is it possible to make this suggestion as a possible enhancement ?
