### ISSUE TITLE
Using new type in avahi-daemon

### ISSUE THREAD

**Issue by cayegara** [lathiat/avahi#238]
Hello I am trying to create a service that uses a new type that is not recorded in /usr/share/avahi/service-types but the daemon is not recognizing it. Is it could be done ? If so, how can I achieve my goal?

**Comment by lathiat** [comment]
The service-types DB is in no way required in order to use a type with Avahi. All it does it help tools like 'avahi-browse' or 'avahi-discover' tell you what the service is. It's purely graphical "extra help".

By all means if you want to add your service to the service-type-database feel free to send a pull request. But it is in no way necessary.
