### ISSUE TITLE
Make gtk-utils installation optional

### ISSUE THREAD

**Issue by pacho2** [lathiat/avahi#24]
We are applying for ages the attached patch on Gentoo to allow us to optionally depend on GTK for gtk-utils... maybe it could be upstreamed finally :)
https://gitweb.gentoo.org/repo/gentoo.git/plain/net-dns/avahi/files/avahi-0.6.30-optional-gtk-utils.patch

Thanks

**Comment by pacho2** [comment]
This is the second one we apply:
https://gitweb.gentoo.org/repo/gentoo.git/plain/net-dns/avahi/files/avahi-0.6.31-fix-install-avahi-discover.patch

**Comment by lathiat** [comment]
Thanks for the patch, I assume that it wouldn't cause you any problems upstream to rename the option used here since people would get a new ebuild update for the new version.  I am thinking of just changing it just to --{enable|disable}-avahi-discover

Also considering the merits of dropping avahi-discover-standalone entirely or at least splitting it out into a separate source tree.  Ubuntu doesn't ship it at all for example and with the name I suspect most people don't use that.

**Comment by evverx** [comment]
To judge from https://gitweb.gentoo.org/repo/gentoo.git/commit/net-dns/avahi?id=a3db7c20bbd129ecc0311fcc6d34b7f5837e6ec4 it seems those patches are no longer used. I think this issue can be closed.

**Comment by evverx** [comment]
> Also considering the merits of dropping avahi-discover-standalone entirely

I think it can be added to https://github.com/lathiat/avahi/issues/516. It would be great if the Gentoo folks could chime in there.
