### ISSUE TITLE
add Mageia support as a linux distribution

### ISSUE THREAD

**Issue by david-geiger** [lathiat/avahi#274]
Hi,

Could it be possible to add also Mageia support for linux distribution in configure build file like Mandriva, fedora, etc..?

Thanks in advance!

Regards,
David

**Comment by evverx** [comment]
That switch is mostly used to include init scripts and given that as far as I can see Mageia uses systemd (where support for those scripts is officially deprecated https://github.com/systemd/systemd/commit/7474097d51907c5cc157a59f311e54949bdd6dba in favor of native unit files) I'm not sure it makes sense to add it there. The unit file should be enough. Closing.

**Comment by evverx** [comment]
I think I get what you mean. I launched a mageia container and it was automatically detected as mandriva by the avahi build system (because it comes with `/etc/mandriva-release` pointing to `/etc/mageia-release`). The init scripts from `initscript/mandriva` were automatically installed too even though they shouldn't have.

@david-geiger I'm not familiar with mandriva and mageia. I wonder if it's safe to fully drop mandriva along with its init script and just detect `/etc/mageia-release` to prevent the avahi build system from thinking that it's fedora?

**Comment by evverx** [comment]
To judge from https://github.com/OpenMandrivaAssociation/avahi/blob/master/avahi.spec (where `--with-distro=mandriva` is used explicitly) the "mandriva" switch can't be removed but it seems the sysv init scripts can be safely removed. Looking https://github.com/OpenMandrivaAssociation/avahi/commit/ae1d928ce21b6255c377d618dac946dbca3a0268#diff-82f20c68baf8e522d15d14fc549bd4c53fed5da27cbe05dcfd4c373a5b534b23R641 @tpgxyz I wonder if it's safe to remove that upstream too?

**Comment by evverx** [comment]
The init scripts were removed in https://github.com/lathiat/avahi/commit/1394f2bcbffc26b79592234ff4a4a47f8c4c3083.

**Comment by tpgxyz** [comment]
Hi, yes you an remove the init scripts, as these are not used anymore. Second the upcoming systemd release is going to drop support for initscripts whatsoever.

**Comment by evverx** [comment]
Now that the scripts are gone I think this issue can be closed. avahi can be built sucessfuly on Mageia/OpenMandriva and it no longer installs anything it shouldn't install there. The `with-distro` switch doesn't control anything else.

@david-geiger @tpgxyz if you are involved in packaging avahi it would be great if you could take a look at https://github.com/lathiat/avahi/issues/516. NixOS, Debian and OpenEmbedded have already expressed their opinion on what can be safely removed but it would be great if more distros could share their thoughts.
