### ISSUE TITLE
avahi-daemon fails if dbus is disabled

### ISSUE THREAD

**Issue by asmithakarun** [lathiat/avahi#284]
I compiled avahi-daemon with "--disable-dbus"

So when dbus is disabled, avahi-daemon fails to start, giving the following logs.

I just wanted to know if the service discovery works when dbus is disabled (which is, will the avahi-daemon be up and active when the dbus is disabled)?

```root@xxx:~# systemctl restart avahi-daemon
Job for avahi-daemon.service failed because a timeout was exceeded.
See "systemctl status avahi-daemon.service" and "journalctl -xe" for details.

root@xxx:~# journalctl -f &

root@xxx:~# -- Logs begin at Mon 2020-04-27 15:57:53 UTC. --
Apr 27 16:46:39 xxx avahi-daemon[577]: Service "xxxx#12" (/services/***.service) successfully established.
Apr 27 16:47:55 xxx systemd[1]: avahi-daemon.service: start operation timed out. Terminating.
Apr 27 16:47:55 xxx avahi-daemon[577]: Got SIGTERM, quitting.
Apr 27 16:47:55 xxx avahi-daemon[577]: Leaving mDNS multicast group on interface eth0.IPv6 with address x:: x: x: x: x.
Apr 27 16:47:55 xxx avahi-daemon[577]: Leaving mDNS multicast group on interface eth0.IPv4 with address x.x.x.x
Apr 27 16:47:55 xxx avahi-daemon[577]: avahi-daemon 0.7 exiting.
Apr 27 16:47:55 xxx systemd[1]: avahi-daemon.service: Failed with result 'timeout'.
Apr 27 16:47:55 xxx systemd[1]: Failed to start Avahi mDNS/DNS-SD Stack.```

**Comment by mvduin** [comment]
The default `avahi-daemon.service` file is written for a dbus-enabled avahi and tells systemd to expect a dbus service registration, hence the service times out when that registration never happens. You'd need to write a custom avahi-daemon.service, put it in `/etc/systemd/system/`, and do `systemctl reenable avahi-daemon`.  I think something like this should work, but I have not tested it:
```ini
[Unit]
Description=Avahi mDNS/DNS-SD Stack
Requires=avahi-daemon.socket

[Service]
Type=forking
ExecStart=/usr/sbin/avahi-daemon -s -D
ExecReload=/usr/sbin/avahi-daemon -r
NotifyAccess=main

[Install]
WantedBy=multi-user.target
Also=avahi-daemon.socket
```

What's the point in doing this though, why would you want to disable dbus support?  Avahi's API for client applications uses dbus, without it there is no way for applications for register, resolve, or browse for services. The only things that still work without dbus are:
1. publishing host and service records through configuration in /etc/avahi/
2. resolving .local hostnames and IPs using gethostbyname()/gethostbyaddr(), provided that libnss-mdns is installed and configured in /etc/nsswitch.conf

**Comment by bendev25689** [comment]
Thankyou, this works,

My reason for doing this is to resolve this (slightly mislabeled) issue where the gtk and kde print dialogues scan for printers independently of the cups server with no way of disabling it, other than disabling dbus:
https://bugs.launchpad.net/ubuntu/+source/cups-filters/+bug/1753509

Since I could find no way of disabling dbus without the avahi-daemon service failing to start, I had no option but to completely disabling avahi-daemon.
This left me with no .local hostname discovery, which is really the only useful purpose avahi serves for me.

For others looking to disable dbus, note that it is not necessary to recompile avahi.
Simply set `enable-dbus=no` in`/etc/avahi/avahi-daemon.conf` and restart avahi-daemon.service
as per this answer: https://askubuntu.com/a/656774

**Comment by mvduin** [comment]
While automatically creating queues for detected printers sounds really annoying (cups-browsed doesn't do this by default but the thread you linked suggests Ubuntu configures it to do so), merely browsing for network printers sounds like it would usually be desirable behaviour. Is the problem just getting an unwieldy long list on a network with lots of printers?

Still, it seems dumb that gtk has no way of disabling this, it can't be that hard to make a config option for it. https://gitlab.gnome.org/GNOME/gtk/-/issues/3314#note_1038840 says "there have been changes to avahi printer discovery recently" but it's not clear what that vague statement means.

Regardless, I suppose if .local name resolution is the only avahi functionality you care about then, since this functionality doesn't require dbus, disabling avahi's dbus interface may be an acceptable workaround until gtk+ fixes this issue. As you point out, you don't need to recompile avahi, you can just disable dbus via avahi-daemon.conf.

Either way, if you disable dbus in avahi you'll need a custom `/etc/systemd/system/avahi-daemon.service` file as I explained in my previous comment. The default service file tells systemd to expect avahi to register itself on dbus, and therefore if you disable dbus in avahi it will appear to systemd that avahi is failing to start. resulting in the issue you reported. This is not an avahi bug, it's systemd doing its job based on what it was told in the avahi-daemon.service file..

Also, I just realized that if you disable dbus in avahi you'll want to disable its dbus service file `/usr/share/dbus-1/system-services/org.freedesktop.Avahi.service`, otherwise it will continue to appear as activatable service on dbus and applications will continue to try communicate with it, resulting in dbus-daemon trying to auto-start the service via systemd but failing with a timeout when it fails to appear on dbus. The best way to fix this on Debian and other dpkg-based distros like Ubuntu is using a diversion:
```sh
sudo dpkg-divert --local --rename --add /usr/share/dbus-1/system-services/org.freedesktop.Avahi.service
```
This will rename the file to `/usr/share/dbus-1/system-services/org.freedesktop.Avahi.service.distrib` and will ensure the file stays renamed even when installing updates of the avahi-daemon package. You can later undo this diversion using the same command but with `--remove` instead of `--add`. Note that dbus-daemon will automatically detect changes to its config files, there's no need to tell it to reload (and definitely never restart dbus-daemon, it will almost certainly break your system until you reboot).


Alternatively, instead of disabling avahi's dbus interface entirely, you could add a policy clause to `/etc/dbus-1/system.d/avahi-dbus.conf` to restrict which users on the system can browse for services, e.g.:
```xml
  <!-- Prevent desktop user from browsing services to keep GTK+ from searching for network printers behind cups-browsed's back -->
  <policy user="YOUR-USERNAME-HERE">
    <deny send_destination="org.freedesktop.Avahi"
          send_interface="org.freedesktop.Avahi.Server" send_member="ServiceBrowserNew"/>
  </policy>
```
This has as benefit that you don't need to mess with systemd or dbus service files, and it selectively disables browsing for services by one specific user without affecting other users (e.g. system services) or other functionality (e.g. service registration). The only concern is how GTK+'s print dialog will react to getting an `org.freedesktop.DBus.Error.AccessDenied` error when attempting to browse for printers.

**Comment by evverx** [comment]
I think it can be closed. @mvduin thank you for looking into this!
