### ISSUE TITLE
No rule to make target bssh.1

### ISSUE THREAD

**Issue by rworkman** [lathiat/avahi#311]
On Slackware devel branch, this occurs: 
>  Making all in man
>  make[2]: Entering directory '/root/tmp/avahi-0.8/man'
>  make[2]: *** No rule to make target 'bssh.1', needed by 'all-am'.  Stop.
>  make[2]: Leaving directory '/root/tmp/avahi-0.8/man'
>  make[1]: *** [Makefile:825: all-recursive] Error 1
>  make[1]: Leaving directory '/root/tmp/avahi-0.8'
>  make: *** [Makefile:735: all] Error 2
I don't see anyone else running into this, but it's not clear at all why it's occurring. The other manual pages are building fine :/

**Comment by rworkman** [comment]
This seems fine in git - how about a new release? :-)
In the meantime, dropping in the bssh.1 and the other affected manual page from a git build solved the problem with 0.8

**Comment by Neustradamus** [comment]
@lathiat: Any news?

**Comment by evverx** [comment]
I think it can be closed. `bssh.1` was fixed in 751be804e891aec5701a059144e2f5cbfc981b36 and the service database was fixed in b5f577b69d108c46afb6c78d56448c208fc217b3. Both those issues could have been caught by `make distcheck` so I opened a PR where it's run to let the CI prevent issues like that going forward.
