### ISSUE TITLE
dig local domain does not reply with the IP

### ISSUE THREAD

**Issue by nickkostov** [lathiat/avahi#337]
I want to be able to dig -x hostname.local using avahi?
is that possible?

**Comment by lathiat** [comment]
In general dig does not work with mDNS because it directly parses /etc/resolv.conf to do normal DNS lookups. And does not use the GLIBC DNS APIs that libnss-mdns extends to work. 

Also -x means reverse DNS lookup by IP so it doesn’t make sense to pass a .local to that. 

If you want to resolve a host name I suggest either:
getent hosts name.local (uses libnss-mDNS or whatever is setup in nsswitch.conf), or
Use “avahi-resolve” which can do both forward and reverse DNS lookups directly through the avahi API (see http://manpages.ubuntu.com/manpages/bionic/man1/avahi-resolve.1.html)

note that by default when using the _minimal mdns variants in /etc/nsswitch.conf libnss-mdns only does reverse DNS lookups for Link local IPs. If you want to do reverse DNS for real IPs including RFC1918 you need to use the avahi API directly using avahi-resolve or switch to the non _minimal variant but that is likely to cause system slowness by waiting 5 seconds for reverse DNS queries to timeout and is not recommended. 

Hope that helps.
