### ISSUE TITLE
Cannot start Avahi-daemon without everyone being allowed to access /run/dbus/system_bus_socket or avahi user being part of the messagebus group.

### ISSUE THREAD

**Issue by someguy736** [lathiat/avahi#349]
If you do not set the user "avahi" to be part of the messagebus group you need to allow complete access to the /run/dbus/system_bus_socket socket file, or use the no-drop-root option when starting the program. This is obviously horrible for security and should be patched somehow ASAP.

**Comment by mvduin** [comment]
Avahi does nothing out of the ordinary, it simply uses libdbus (the reference dbus implementation) to connect to the system bus in the default, recommended way.  If you have a problem with how this works, then you have a problem with dbus itself, not with avahi.

It's really unclear what you're even trying to describe, /run/dbus/system_bus_socket socket is normally world-writable (0666) since write-permission of sockets controls the ability to connect to the socket and the system bus is supposed to be accessible by everyone. Fine-grained access control to the system bus is available through dbus-daemon's configuration/policy files.

Every linux system I've been able to check (debian buster, debian bullseye, debian sid, centos 7.7) have the following permissions:
```
drwxr-xr-x 2 root root /run/dbus
srw-rw-rw- 1 root root /run/dbus/system_bus_socket
```
and avahi, when installed, is not member of the `messagebus` group nor any other group other than its own `avahi` group.

**Comment by spacehobo** [comment]
I am trying to run avahi on Termux, which is a limited environment that runs under Android.  As such, we do not have access to add users, and a `getpwnam('avahi')` will fail.  The `--no-drop-root` option does a good job of preventing `drop_root()` from running, but it still runs the user management parts of `make_runtime_dir()` per https://github.com/lathiat/avahi/blob/master/avahi-daemon/main.c#L1408

If I'm running without dbus and with `--no-drop-root` set, can we assume I just want to run this as the current user, and not try to inspect the `passwd` database?

See also termux/termux-packages#8111

**Comment by mvduin** [comment]
Uhh, why are you trying to run Avahi on android?  Android already runs an mDNS stack, accessed via the "Network Service Discovery" API.

I do agree that with --no-drop-root it ought to just use the current user's runtime dir instead of using assumptions compiled into the executable, though Avahi is normally always run as system service and current behaviour isn't really a problem in that case. And if you really want to run Avahi as normal user then there's always the option of compiling Avahi with AVAHI_USER and AVAHI_GROUP configured to the user and group you want to run it as, and AVAHI_DAEMON_RUNTIME_DIR to that user's runtime directory.

I also don't see how any of this relates to whatever you attempted to originally describe in this issue. You seem to be describing something completely different now.

**Comment by spacehobo** [comment]
I am sure that Android has a Java API for exposing a hostname, but that's not something I can make use of from a Termux shell very easily.  And the termux packaging can't predict what the user for Termux will be at runtime on Android.

I didn't open this issue, but merely wanted to illustrate some other assumptions being made in the code about the `avahi` user.  I can open a new issue if that will help.

**Comment by mvduin** [comment]
Ah I wasn't paying attention, I thought it was a reply from the original poster. But yeah, your comment seems completely off-topic here, I'd suggest you create a new issue, or better yet a pull request ;-)  BTW, that java API connects via a unix socket to the actual [mDNS daemon](https://android.googlesource.com/platform/external/mdnsresponder/), which is a fairly old version of Apple's mDNSResponder. If that socket (`/dev/socket/mdnsd` group `inet` according to the rc file) is accessible and you only need .local name resolution, presumably installing its libnss-mdns would suffice?

**Comment by evverx** [comment]
The system bus is usually world-writable. That's how D-Bus works. Closing.

**Comment by kuvaldini** [comment]
is there a way to let only group avahi publish new services?

**Comment by mvduin** [comment]
> is there a way to let only group avahi publish new services?

Which process is allowed to send what dbus messages is controlled by config files (typically in `/usr/share/dbus-1/system.d/` and `/etc/dbus-1/system.d/`). You can use that to limit access to the `EntryGroupNew` method to certain users or groups.

Something like this placed in `/etc/dbus-1/system.d/avahi-custom.conf` should work I think:
```xml
<!DOCTYPE busconfig PUBLIC
          "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
          "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <policy context="default">
    <deny send_destination="org.freedesktop.Avahi" send_member="EntryGroupNew"/>
  </policy>
  <policy group="avahi">
    <allow send_destination="org.freedesktop.Avahi" send_member="EntryGroupNew"/>
  </policy>
</busconfig>
```

**Comment by kuvaldini** [comment]
archlinux already has `/usr/share/dbus-1/system.d/avahi-dbus.conf`
```xml
<!DOCTYPE busconfig PUBLIC
          "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
          "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>

  <!-- Only root or user avahi can own the Avahi service -->
  <policy user="avahi">
    <allow own="org.freedesktop.Avahi"/>
  </policy>
  <policy user="root">
    <allow own="org.freedesktop.Avahi"/>
  </policy>

  <!-- Allow anyone to invoke methods on Avahi server, except SetHostName -->
  <policy context="default">
    <allow send_destination="org.freedesktop.Avahi"/>
    <allow receive_sender="org.freedesktop.Avahi"/>

    <deny send_destination="org.freedesktop.Avahi"
          send_interface="org.freedesktop.Avahi.Server" send_member="SetHostName"/>
    <deny send_destination="org.freedesktop.Avahi"
          send_interface="org.freedesktop.Avahi.Server2" send_member="SetHostName"/>
  </policy>

  <!-- Allow everything, including access to SetHostName to users of the group "network" -->
  <policy group="network">
    <allow send_destination="org.freedesktop.Avahi"/>
    <allow receive_sender="org.freedesktop.Avahi"/>
  </policy>
  <policy user="root">
    <allow send_destination="org.freedesktop.Avahi"/>
    <allow receive_sender="org.freedesktop.Avahi"/>
  </policy>
</busconfig>
```

**Comment by mvduin** [comment]
@kuvaldini yes and it allows everyone access to everything except `SetHostName`, putting the snippet I showed in `/etc/dbus-1/system.d/` will augment these rules to deny `EntryGroupNew` to everyone who's not in group `avahi`
