### ISSUE TITLE
Avahi insist that `/run/avahi-daemon` must belong to `avahi:avahi` even when ran with a different user and `--no-chroot` `--no-drop-root`

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [lathiat/avahi#432]
Some form of this has been mentioned in #349 by @mvduin

Assume you are running avahi with user "X" (where "X" is **NOT** "avahi").
`avahi --no-drop-root --no-chroot` will bail out if the directory `/run/avahi-daemon` does not belong to `avahi:avahi`

It is hard to understand the reason for that behavior... especially since `avahi` does not care about the permissions (eg: 777 will be fine...). The only thing that should really matter here is that `/run/avahi-daemon` can be created / is writable.

Code is here:

https://github.com/lathiat/avahi/blob/778fadb71cb923eee74f3f1967db88b8c2586830/avahi-daemon/main.c#L1441

The problem is manifest if you need to run avahi with a specific user that is not avahi and:
* `/run/avahi-daemon` does not already exist AND have the right ownership (AND permissions)
* or the avahi user simply does not exist

Unless I am missing something and there is really a reason for avahi to demand that a hardcoded username exist and owns the runtime directory in that case (`--no-root-drop`), I would suggest this is just removed in favor of a simpler creation/writable check.

**Comment by dubo-dubon-duponey** [comment]
[Comment](https://github.com/lathiat/avahi/issues/349#issuecomment-984393040) was from @spacehobo actually - apologies for the ping, mvduin.

**Comment by evverx** [comment]
> It is hard to understand the reason for that behavior.

`git log` shows that it was introduced in d865d04651f5563c2b3257a8f2073c9eac5fcfe0 to "create /var/run/avahi securely". Before that it was possible for any unprivileged user to DOS avahi by creating a bogus socket.

> The only thing that should really matter here is that /run/avahi-daemon can be created / is writable

On most systems it can only be created by `root`.

Could you expand on what your use case is?

**Comment by mvduin** [comment]
I agree that if Avahi is run as normal (non-root) user then it ought to just create the socket in a normal way instead of using this code which is clearly written under the assumption that it's being run as root and will be dropping to the configured avahi user/group.

**Comment by evverx** [comment]
This use case is kind of unusual and it's already supported by setting `--with-avahi-user=` and `localstatedir` if it's really needed.

To judge from https://github.com/termux/termux-packages/pull/17079 even the termux use case is no longer relevant.

**Comment by apostasie** [comment]
Thanks folks. Appreciate the feedback here.

@evverx

1. what I am saying is that if avahi does run as user `whateveruser` it does not make sense to check if `/run/avahi-daemon` belongs to user `avahi` - instead, it should check that it belongs to `whateveruser`.

2. `--with-avahi-user` is a configure option right? I would rather not have to roll my own here, and it will not address my use case

In the current state of affairs, this ^ means that it is quite backwards to run the avahi daemon as any other user than `avahi`.

> Could you expand on what your use case is?

Of course.
I am running avahi inside a container - no root - where the operator decides which user the container will be started under (hence which user avahi will be started with).

What I would have expected is that:
1. operator starts container with user `whateveruser` 
2. `avahi --no-drop-root --no-chroot` is started, obviously under user `whateveruser`
3. `avahi` checks that `/run/avahi-daemon` belongs to `whateveruser`, since this is what avahi is running with
4. happy :)

The problem I am describing is that in step 3, avahi instead wants the folder to belong to user `avahi`.

**Comment by apostasie** [comment]
and yeah, I am the O.P.
Pro vs. personal account, same person :-)

**Comment by evverx** [comment]
> I am running avahi inside a container - no root - where the operator decides which user the container will be started under

This use case is kind of unusual either in 2023. Why wouldn't containers be rootless on the outside but with `root` inside the user namespace? It would also automatically solve all the DBus issues.

**Comment by apostasie** [comment]
I am not using DBus (which does not require root anyhow).

Also, not everybody wants to mess up with user namespaces mapping - especially when you actually do not need root inside.

I do understand if avahi does not want to address this - but it is IMHO unusual in 2023 for any process running as non root to ask that a folder belong to a different user than the one it is run with...

**Comment by apostasie** [comment]
I am not using DBus (which does not require root anyhow).

Also, not everybody wants to mess up with user namespaces mapping - especially when you actually do not need root inside.

I do understand if avahi does not want to address this - but it is IMHO unusual in 2023 for any process running as non root to ask that a folder belong to a different user than the one it is run with...

**Comment by evverx** [comment]
> not everybody wants to mess up with user namespaces mapping - especially when you actually do not need root inside

Understood.

It would still be necessary to mess with network interfaces/ports to expose that container to the host/actual network. I'm not sure how it's done without `root`.

> it is IMHO unusual in 2023 for any process running as non root

avahi is run as non root these days just because back in 2005 it was audited. Before that it happily ran as root and didn't drop any privileges. It has always been a system daemon that hasn't been supposed to be run by unprivileged users.

**Comment by evverx** [comment]
Having reread this thread it seems to me that the operator (or whoever is responsible for providing you with containers) doesn't want to give you enough privileges to start launching daemons sending/receiving packets. Even if it was possible to launch it inside those containers as a random unprivileged user the surrounding infrastructure like firewalls, network interfaces and so on is unlikely to be set up either (and out of reach for those containers from inside those containers). All in all it doesn't work in general. There are niche setups where it can be made to work but I believe they should have no problem with compiling their own avahi with their own configuation options (and they should do it anyway because large distros like Debian, Ubuntu, Fedora and so on are unlikely to ever allow random users to start launching avahi left and right). Closing. If there are any other use cases (or if I missed something) please let me know and I can always reopen the issue.

**Comment by evverx** [comment]
> I am not using DBus (which does not require root anyhow).

I missed that part. Something privileged enough to write to system directories has to install the policies preventing random users from claiming to be avahi-daemon on D-Bus where another system D-Bus daemon can find them. This sort of thing is usually done in "system" containers where `root` is available and that use case perfectly works as is with all major distros as base images.
