### ISSUE TITLE
One service IPv4/6, one service IPv4 only

### ISSUE THREAD

**Issue by TobixDS** [lathiat/avahi#463]
Hi,
perhaps I have a misunderstanding, but I have no idea where I could ask.

I have one host which offers two services: 
e.g. SSH and Foo.
I would like to have SSH reachable by IPv4 and IPv6, but the Foo service is IPv4 capable only.

If I now specify in foo.services
<service protocol="ipv4">

a Windows machine browsing for services (using Bonjour) gets the identical hostname for both services and therefor gets both IPv4 and IPv6 addresses for the hostname.
But the client for the foo service stumbles over the IPv6 addresses.

Any ideas / options beside switching off IPv6 completely?

Thanks

**Comment by nkarstens** [comment]
We've also run into this in the past. I'll relate our conclusions; hopefully it will help you out, and if someone else has a better idea of how to do this then they can correct me!

It seems counterintuitive, but there isn't really a way to do this. To understand why not it is helpful to know what is happening at a protocol level with the various DNS records involved.

A service is advertised using an SRV record, which contains two fields used to contact the service: host name and port. The A (IPv4) or AAAA (IPv6) record associates a host name with an IP address. Because the mapping of service to host name and host name to address is decoupled, there is no direct way in the protocol to indicate that a service is only accessible over only IPv4 or IPv6.

Avahi seems to have support for indirectly indicating this by only transmitting the SRV record over IPv4 or IPv6 (see the `protocol` parameter of `avahi_entry_group_add_service()`). This is not a technique supported by all mDNS responders, though. I reached out to the Bonjour maintainers about this back in 2017 and their advice was to always support both IPv4 and IPv6. If you don't, then the client has to know which protocol to use.

Another way to do this that would work with Bonjour would be to manually create a second A record for your host that maps something like "yourhost-ipv4.local" to the IPv4 address. Do not create any AAAA record for that host. Pair that with an SRV record that maps the service to "yourhost-ipv4.local" and the port.

**Comment by pemensik** [comment]
I admit it is expected in general it is the connectivity of the host, which limits offered services. Not support per application advertised. I admit there is no way to specify service is one family only. Not even on the protocol level, so API is unable that correctly.

I agree that only announcing multiple names for the host, one with both address families and another one with just a single family. Or just push foo vendor to provide support for both families for that service. But I admit the clients for that service should be able to cope with service unavailable on one of addresses. Especially if the implementation is known to support just one family.

Can you share, which kind of service is limited this way?

**Comment by TobixDS** [comment]
Thanks both of you for the extensive answers. Both confirm that my understanding is correct.
Changing the foo software to support IPv6 is only possible future versions. But unfortunately there will be - at least for a migration period - legacy versions in the field and they just cannot handle IPv6. So enabling IPv6 for SSH is not an option as it would cause trouble with the existing software.
I will checkout the idea to create different hostnames.
