### ISSUE TITLE
Support for multicast - SSDP traffic . [UPNP - 239.255.255.250 - UDP 1900]

### ISSUE THREAD

**Issue by gtotheit** [lathiat/avahi#53]
Any chance of supporting SSDP in the near future ? Proxying multicast SSDP traffic in between different broadcast domains.

**Comment by nick599** [comment]
I disagree with this. 

1) Upnp has had some serious vulnerabilities in the past. Search "upnp rapid7" or "metasploit upnp ssdp_msearch" for more info. 

2) Adding additional services, eg upnp, also increases the attack surface of the system, since more services would be running.

Both of these make the product less secure.

**Comment by lathiat** [comment]
At this time Avahi is focused on Multicast DNS specifically, and don't intend to add support for other protocols.  But thanks for the suggestion, it is appreciated anyway.
