### ISSUE TITLE
Become definitive upstream for nss-mdns

### ISSUE THREAD

**Issue by agoode** [lathiat/avahi#64]
For context, see
* https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211345
* https://bugs.chromium.org/p/chromium/issues/detail?id=626377

I would like to propose merging the nss-mdns package into this one, making avahi the definitive upstream for that package. nss-mdns has a hard requirement on Avahi in its recommended configuration, and there are outstanding patches from FreeBSD that have not been accepted upstream.

The existing upstream is at http://0pointer.de/lennart/projects/nss-mdns/ and http://git.0pointer.net/nss-mdns.git/ but has received no updates since 2007.

I can prepare the patches if this idea is acceptable. My further plans include:
* unifdef many of the compile options, specifically the non-Avahi support which has been long deprecated
* fix up and merge the outstanding FreeBSD ports patches
* then finally look into adding some new functionality to nss-mdns

My ultimate goal here is to allow Avahi + nss-mdns to coexist with DNS servers that provide .local resolution, using the SOA algorithm described here: https://support.apple.com/en-us/HT201275. This would allow the elimination of the problematic scripts currently used by distributions that hard-stop Avahi when such a configuration is detected.

**Comment by lathiat** [comment]
+1 this sounds great. I also have code to support interface indexes/scopes so link local IPv6 will work properly which means IPv6 can be enabled by default and generally work properly.

I suspect However I also need to pay attention to systemd-resolved. Seems they implemented a mini mdns stack for some strange reason already but the good news is that Avahi support could use dbus rather than the UNIX socket and thus also easy to add interface index/scopes for that.

I'll set it up and happily take your patches.

**Comment by agoode** [comment]
Yes, I looked at systemd-resolved and thought "one problem at a time" 😺

**Comment by agoode** [comment]
@lathiat Can you take a look at the pull request and let me know if it's what you're looking for?

**Comment by agoode** [comment]
See https://github.com/lathiat/nss-mdns.

**Comment by lemenkov** [comment]
Cool! It's great to see that nss-mdns receives an attention after a long hiatus! Thanks @agoode !
