### ISSUE TITLE
Avahi 0.6.31 - Centos 7 - is not working with Sierra version

### ISSUE THREAD

**Issue by Mishiago** [lathiat/avahi#86]
Hi,

After upgrading El-Capitan to Sierra version, Time Machine Backup stop working properly.

I'm trying to add Time Machine Disk, i saw the available disk, but got: "OSStatus error:65"

I tried to add a disk via: Go-> Connect to server-> afp://IPAddress - working perfectly.

please Advise.

**Comment by lathiat** [comment]
I'd say this is related to netatalk (which is using avahi to advertise the service) rather than Avahi itself.  I'd check with the netatalk project for assistance unless you have a more firm understanding of there being some avahi-specific interopability issue.  No such issues as far as I am aware.  Most likely some change in the AFP handling in Sierra.
